### ISSUE TITLE
Make sure the 3D tracks look right

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/TrainCraft-1.8.9#11]
Vanilla normal:
![Normal rails](https://cloud.githubusercontent.com/assets/3751138/12872800/a970240e-cda4-11e5-8e83-87222a1bd77a.png)

Vanilla unpowered speed (golden) tracks:
![Unpowered speed](https://cloud.githubusercontent.com/assets/3751138/12872803/b6253234-cda4-11e5-83f3-addc278a8b02.png)

Vanilla powered speed (golden) tracks:
![Powered speed](https://cloud.githubusercontent.com/assets/3751138/12872806/c1d03c0a-cda4-11e5-8b59-852ef7f2d8fc.png)

Vanilla unpowered Activator (light tnt) tracks:
![Unpowered activator](https://cloud.githubusercontent.com/assets/3751138/12872808/d2ea3ea0-cda4-11e5-9ff1-b987860334a7.png)

Vanilla powered Activator (light tnt) tracks:
![powered activator](https://cloud.githubusercontent.com/assets/3751138/12872811/dd1d8ec2-cda4-11e5-843b-d3cba51c0132.png)

Vanilla Detector tracks still a WIP atm. I will add them soon.

TrainCraft Ascending:
![From one side](https://cloud.githubusercontent.com/assets/3751138/12872826/723765aa-cda5-11e5-8a19-ddc72a838034.png)
![From the other side](https://cloud.githubusercontent.com/assets/3751138/12872827/7a25475a-cda5-11e5-8fa9-72e4f5b7617d.png)

TrainCraft Diagonal:
![Diagonal](https://cloud.githubusercontent.com/assets/3751138/12872839/cff1776c-cda5-11e5-927b-f6d04cd8174c.png)

TrainCraft Curved:
![Curved 4 wide](https://cloud.githubusercontent.com/assets/3751138/12872843/27e0d60c-cda6-11e5-840f-3279ea84ff5d.png)

**Comment by NitroxydeX** [comment]
Good work! keep it up.

will there be a way to use any material under the tc ascending tracks?
Also love the 45° curve! :)

**Comment by AlexIIL** [comment]
There will probably be a way for mods to add blocks that are usable in ascending tracks, but that's not happening right now. Also more than 10 block types will be usable in the future :)

**Comment by mariodk** [comment]
Really really hope when railcraft comes for 1.8.9
Railcraft / this mod will hold hands and be best friends
want to have automated Trains with train routes with automatic switches(bigger curvers on those too instead of 90°) and use item/fluid loader from railcraft on carts/trains on this mod 

so my Dream Minecraft Train system can become true

**Comment by AlexIIL** [comment]
It would be good to have railcraft support in the future :) But I'll have to talk to @CovertJaguar about that to see what support we can have.

**Comment by mariodk** [comment]
Good becuase Railcraft (for me) has always needed atleast Diagonal rails since if building tracks like this: http://i.stack.imgur.com/jS6db.png
the train / minecart anyway Runs Diagonal but the tracks just look out of place even i that dont know so much to coding knows railcraft could just added a special rail so if build like this picture the textures will not be curved rail texture but use Diagonal rails texture
and also Block under slope rails like Carpenter´s block has now 
but kinda also hoping for a Backport 1.7.10 (atleast with the first releases of this mod if possible)
since many mods is still in 1.7.10 and will be for some time but its up to you 

also a other idea:
kinda like flans has packs for guns/tanks/planes and stuff
it would be nice with trains aswell
so people choose what trains/carts(if they want any or just want the bigger slopes/curvers part of the mod) they want on the modpack/Server like if they dont want too many
they can just add x1 stream, 1x dissel(BC fuel), 1x electic (RF/T or EU/T) train and afew carts

not sure how people would be able to make custom trains/carts for the mod but that would also be awesome if they could do that
i will love to be able to make train models/textures and add them to the mod some how and im sure others want that too (i think it was highly requested on the old traincraft aswell)

**Comment by AlexIIL** [comment]
@mariodk This is a rewrite of the original TrainCraft for 1.6.4, so there will be a lot of trains in the future to choose from, and they will all be contactable to each other in whatever way you choose :)

Custom trains will probably be able to be done via addons, which means that its is possible to add them if you can code.

There will not be a 1.7.10 version, as its stupidly difficult to maintain a mod over more than one MC version.

Oh, and this is VERY EARLY look- all train stuff is barely done (there are 2 rolling stock models atm, and neither of them have textures) and they don't currently connect, so don't expect this to be out anytime soon.

**Comment by NitroxydeX** [comment]
If you make the vanilla ones 3D like in your last commit you should not register a 1 block rail in TC. Would be the same?

**Comment by AlexIIL** [comment]
They are not actually the same though: TC tracks never move once placed (so they orient themselves based on what direction you are looking, rather than what other tracks are around them). Also the same block is used for diagonal as well as straight, so I don't use up any more block space. Also ascending tracks work differently in TC (you cannot go up by one block in one block).

**Comment by NitroxydeX** [comment]
Alright. Okay :)

**Comment by Tar-Gilkaltar** [comment]
Good work :) Go on!

**Comment by AlexIIL** [comment]
This issue was moved to AlexIIL/TrainCraft-Ideas#2

**Comment by AlexIIL** [comment]
I'm moving all ideas/suggestions/feedback to http://github.com/AlexIIL/TrainCraft-Ideas/issues
